version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    auto-merge: true
    commit-message:
      prefix: 'npm'
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    auto-merge: true
    commit-message:
      prefix: 'github-actions'
    open-pull-requests-limit: 10
