name: 'Docker Compose Cache'
description: 'Caches Docker images from Docker Compose files to speed up builds. Supports digest checks and image exclusion.'
author: 'Seiji Kohara (https://github.com/seijikohara)'
branding:
  icon: 'zap'
  color: 'blue'
inputs:
  compose-files:
    description: >
      Path(s) to the Docker Compose file(s).
      Specify multiple files using multiline string with pipe (|):
        compose-files: |
          docker-compose.yml
          docker-compose.prod.yml
      If omitted, defaults to searching for default compose files.
    required: false
  exclude-images:
    description: >
      Images to exclude from caching.
      Specify multiple images using multiline string with pipe (|):
        exclude-images: |
          mysql:8.0
          redis:alpine
    required: false
  cache-key-prefix:
    description: 'Prefix for the generated cache key.'
    required: false
    default: 'docker-compose-image'
  skip-latest-check:
    description: 'Skip checking the latest version of Docker images from the registry. When enabled, cached images will be used without verifying if newer versions are available.'
    required: false
    default: 'false'
outputs:
  cache-hit:
    description: "Boolean value ('true' or 'false') indicating if *all* required images were restored from cache (and digests matched). Example: 'true'"
  image-list:
    description: 'JSON array of image details with information about each image. Example: ''[{"name":"mysql:8.0","platform":"linux/amd64","status":"Cached","size":524288000,"processingTimeMs":1200.5,"cacheKey":"docker-compose-image-mysql-8.0-linux-amd64-none-sha256:digest"},{"name":"redis:alpine","platform":"linux/amd64","status":"Pulled","size":32768000,"processingTimeMs":3500.2,"cacheKey":"docker-compose-image-redis-alpine-linux-amd64-none-sha256:digest"}]'''
runs:
  using: 'node20'
  main: 'dist/index.js'
