# A simple compose file for testing the caching action

services:
  web_server:
    # A common, moderately sized web server image
    image: nginx:stable-alpine
    ports:
      - '8081:80' # Use a different port than default 80 if needed

  database:
    # A popular database image, often larger
    image: postgres:16-alpine
    restart: always
    environment:
      # Use dummy credentials for testing
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache_store:
    # A common in-memory cache image
    image: redis:7-alpine
    restart: always

volumes:
  postgres_data: # Define the volume used by the database
