name: Auto-Merge Dependabot PRs (npm & GitHub Actions)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  auto-merge-dependabot-prs:
    name: Auto-Merge Dependabot Dependency PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.DEV_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.DEV_AUTOMATION_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Auto-merge Dependabot PR
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # Wait for CI checks to pass
          gh pr checks ${{ github.event.pull_request.number }} --watch
          
          # Approve the PR first
          gh pr review ${{ github.event.pull_request.number }} --approve
          
          # Enable auto-merge with squash strategy
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash --delete-branch
