name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]

    outputs:
      node-version: ${{ steps.set-output.outputs.node-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set matrix output
        id: set-output
        run: echo "node-version=${{ matrix.node-version }}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build TypeScript
        run: npm run build

      - name: Package action using ncc
        run: npm run package

      - name: Check for uncommitted changes in dist/
        run: |
          if ! git diff --exit-code --quiet dist/; then
            echo "Detected uncommitted changes in dist/ after build. Please run 'npm run package' and commit the changes."
            exit 1
          fi

  build-and-test-summary:
    name: Build and Test Summary
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Report successful completion
        run: |
          echo "### Build and Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ All build and test jobs for Node.js completed successfully." >> $GITHUB_STEP_SUMMARY

      - name: Print Node.js versions tested
        run: |
          echo "Tested Node.js versions: 20.x, 22.x" >> $GITHUB_STEP_SUMMARY
