name: Auto Process and Merge NPM Dependency Updates

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  auto-process-npm-dependencies:
    name: Process and Merge NPM Dependency Updates
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && (startsWith(github.event.pull_request.title, 'npm') || startsWith(github.event.pull_request.title, 'github-actions')) && github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout npm dependency PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Check if rebase is needed for npm PR
        id: check-rebase
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          BASE_SHA=$(git rev-parse origin/${{ github.event.pull_request.base.ref }})
          PR_BASE_SHA=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
          if [ "$BASE_SHA" != "$PR_BASE_SHA" ]; then
            echo "rebase_needed=true" >> $GITHUB_OUTPUT
          else
            echo "rebase_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Rebase npm PR if needed
        if: steps.check-rebase.outputs.rebase_needed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git rebase origin/${{ github.event.pull_request.base.ref }}

      - name: Verify with npm tests
        run: npm run test

      - name: Run npm package build
        run: npm run package

      - name: Commit packaged npm dependencies
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "chore: update package with latest npm dependencies" || echo "No package changes to commit"

      - name: Bump npm version for dependency update
        run: |
          npm version patch -m "chore: bump version for npm dependency updates"

      - name: Push changes and version tags
        run: |
          git push --force
          git push --tags

      - name: Enable auto-merge for npm dependency PR
        run: |
          gh pr merge "$PR_URL" --auto --merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve npm dependency PR
        run: |
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
