name: Update Major Version Tags

on:
  workflow_dispatch:

jobs:
  update-major-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update major version tags
        run: |
          echo "### 📌 Updating Major Version Tags" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Major Tag | Latest Semantic Tag | Commit SHA |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|----------------------|------------|" >> $GITHUB_STEP_SUMMARY

          # Get all semantic version tags and sort them
          git tag \
            | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V \
            | while read tag; do
                version=$(echo "$tag" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
                major=$(echo "$version" | cut -d. -f1)
                major_tag="v$major"
                commit_sha=$(git rev-list -n 1 "$tag")

                # Store latest semantic tag per major version
                echo "$major_tag $tag $commit_sha"
              done \
            | awk '{ a[$1]=$2; b[$1]=$3 } END { for (k in a) print k, a[k], b[k] }' \
            | sort \
            | while read major_tag latest_tag commit_sha; do
                short_sha=$(git rev-parse --short "$commit_sha")
                git tag -fa "$major_tag" "$commit_sha" -m "chore(release): update $major_tag to point to $latest_tag"
                git push origin "$major_tag" --force
                echo "| \`$major_tag\` | \`$latest_tag\` | \`$short_sha\` |" >> $GITHUB_STEP_SUMMARY
              done
