name: Update Major Version Tag

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Semantic version tag to process (e.g., v1.2.3)'
        required: true
        type: string
      commit_sha:
        description: 'Target commit SHA to tag (optional; defaults to HEAD)'
        required: false
        type: string

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    concurrency:
      group: major-tag-${{ github.ref_name || inputs.tag_name }}
      cancel-in-progress: true

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags explicitly
        run: git fetch --tags

      - name: Get version from input or tag
        id: get-version
        run: |
          if [ -n "${{ github.event.inputs.tag_name }}" ]; then
            TAG_NAME="${{ github.event.inputs.tag_name }}"
          else
            TAG_NAME="${GITHUB_REF_NAME}"
          fi

          VERSION=$(echo "$TAG_NAME" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          echo "major_version=$MAJOR_VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Configure Git Credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update or create major version tag
        id: update_tag
        env:
          MAJOR_VERSION: ${{ steps.get-version.outputs.major_version }}
          PUSHED_TAG_NAME: ${{ steps.get-version.outputs.tag_name }}
          COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
        run: |
          MAJOR_VERSION_TAG="v${MAJOR_VERSION}"
          if [ -n "$COMMIT_SHA" ]; then
            TARGET_COMMIT="$COMMIT_SHA"
          else
            TARGET_COMMIT=$(git rev-parse HEAD)
          fi
          SHORT_COMMIT_SHA=$(git rev-parse --short "$TARGET_COMMIT")

          git tag -fa "$MAJOR_VERSION_TAG" "$TARGET_COMMIT" -m "chore(release): update or create $MAJOR_VERSION_TAG based on $PUSHED_TAG_NAME ($TARGET_COMMIT)"

          git push origin "$MAJOR_VERSION_TAG" --force

          echo "### Major Version Tag Updated or Created" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Action        | Trigger Tag         | Major Tag           | Commit SHA |" >> $GITHUB_STEP_SUMMARY
          echo "|---------------|---------------------|---------------------|------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Updated/Created | \`${PUSHED_TAG_NAME}\` | \`${MAJOR_VERSION_TAG}\` | \`${SHORT_COMMIT_SHA}\` |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Major version tag **${MAJOR_VERSION_TAG}** was **updated or created** to point to commit \`${SHORT_COMMIT_SHA}\` (triggered by \`${PUSHED_TAG_NAME}\`)." >> $GITHUB_STEP_SUMMARY
